[workspace]
resolver = "2"
members = [
    "alliance",
    "alliance-entity",
    "alliance-migration",
    "blockscout",
    "blockscout-entity",
    "blockscout-migration",
    "smart-contract-fiesta",
    "smart-contract-fiesta-entity",
    "smart-contract-fiesta-migration",
    "job-queue",
]
