type: google.api.Service
config_version: 3

http:
  rules:
    #################### DomainsExtractor ####################
    - selector: blockscout.bens.v1.DomainsExtractor.GetDomain
      get: /api/v1/{chain_id}/domains/{name}

    - selector: blockscout.bens.v1.DomainsExtractor.ListDomainEvents
      get: /api/v1/{chain_id}/domains/{name}/events

    - selector: blockscout.bens.v1.DomainsExtractor.ResolveDomainName
      get: /api/v1/{chain_id}/domains/{name}/resolve

    - selector: blockscout.bens.v1.DomainsExtractor.ResolveAddress
      get: /api/v1/{chain_id}/addresses/{address}/resolve

    - selector: blockscout.bens.v1.DomainsExtractor.BatchSearchAddressNames
      post: /api/v1/{chain_id}/address-names:batch-search
      body: "*"

    #################### Health ####################

    - selector: blockscout.bens.v1.Health.Check
      get: /health
