[package]
name = "alliance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alliance-entity = { path = "../alliance-entity" }
alliance-migration = { path = "../alliance-migration" }
job-queue = { path = "../job-queue", features = ["logic"] }

anyhow = "1.0.75"
blockscout-display-bytes = "1.0.0"
blockscout-service-launcher = { version = "0.9.0", features = ["database-0_12"] }
futures = "0.3.29"
hex = "0.4.3"
proxy-verifier-proto = { git = "https://github.com/blockscout/blockscout-rs", rev = "3c5c387" }
reqwest = "0.11"
reqwest-middleware = "0.2.3"
reqwest-retry = "0.2.3"
sea-orm = "0.12.4"
serde = "1.0.190"
serde_json = "1.0.108"
serde_path_to_error = "0.1.14"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.40"
url = { version = "2.3.1", features = ["serde"] }