[server]
addr = "0.0.0.0:8050"

[blockscout]
base_url = "https://blockscout.com"
concurrent_requests = 10
instances = [
    '{"title": "Goerli", "url": "https://eth-goerli.blockscout.com", "id": "eth/goerli"}',
    '{"title": "Mainnet", "url": "https://eth.blockscout.com/", "id": "eth/mainnet"}',
]
request_timeout = 60

[jaeger]
enabled = false
agent_endpoint = "localhost:6831"
