swagger: "2.0"
info:
  title: bens.proto
  version: version not set
tags:
  - name: DomainsExtractor
  - name: Health
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/{chainId}/domains/quick-resolve:address:
    post:
      operationId: DomainsExtractor_QuickResolveAddress
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1QuickResolveResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: chainId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              address:
                type: string
      tags:
        - DomainsExtractor
  /api/v1/{chainId}/domains/quick-resolve:addresses-batch:
    post:
      operationId: DomainsExtractor_QuickResolveAddresses
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1QuickResolveResponseManyDomains'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: chainId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              addresses:
                type: array
                items:
                  type: string
      tags:
        - DomainsExtractor
  /api/v1/{chainId}/domains/quick-resolve:domain:
    post:
      operationId: DomainsExtractor_QuickResolveDomain
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1QuickResolveResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: chainId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      tags:
        - DomainsExtractor
  /api/v1/{chainId}/domains/quick-resolve:domains-batch:
    post:
      operationId: DomainsExtractor_QuickResolveDomains
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1QuickResolveResponseManyAddresses'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: chainId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              names:
                type: array
                items:
                  type: string
      tags:
        - DomainsExtractor
  /api/v1/{chainId}/domains:search:
    post:
      operationId: DomainsExtractor_SearchDomain
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DetailedDomain'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: chainId
          description: / The chain (network) where domain search should be done
          in: path
          required: true
          type: string
          format: uint64
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                title: / Name of domain, for example vitalik.eth
      tags:
        - DomainsExtractor
  /api/v1/{chainId}/domains:search-reverse:
    post:
      operationId: DomainsExtractor_SearchReverseDomain
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SearchReverseDomainResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: chainId
          description: / The chain (network) where domain search should be done
          in: path
          required: true
          type: string
          format: uint64
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              address:
                type: string
                title: / Address of EOA or contract
              resolvedTo:
                type: boolean
                title: / Include domains resolved to the address
              ownedBy:
                type: boolean
                title: / Include domains owned by the address
      tags:
        - DomainsExtractor
definitions:
  HealthCheckResponseServingStatus:
    type: string
    enum:
      - UNKNOWN
      - SERVING
      - NOT_SERVING
      - SERVICE_UNKNOWN
    default: UNKNOWN
    description: ' - SERVICE_UNKNOWN: Used only by the Watch method.'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1DetailedDomain:
    type: object
    properties:
      domain:
        $ref: '#/definitions/v1Domain'
        title: / Optinal. Basic domain info
      history:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1DomainEvent'
        title: / List of domain events
  v1Domain:
    type: object
    properties:
      id:
        type: string
        title: / Unique id for the domain, also known as nodehash
      name:
        type: string
        title: / The human readable name, if known. Unknown portions replaced with hash in square brackets (eg, foo.[1234].eth)
      tokenId:
        type: string
        format: uint64
        title: / Integer representation of labelhash
      owner:
        type: string
        title: / The account that owns the domain
      resolvedAddress:
        type: string
        title: / Optinal. Resolved address of this domain
      registrant:
        type: string
        title: / Optinal. The account that owns the ERC721 NFT for the domain
      expiryDate:
        type: string
        format: uint64
        title: / Optinal. Unix timestamp of expiry date. None means never expires
      registrationDate:
        type: string
        format: uint64
        title: / Unix timestamp of regisration date
      otherAddress:
        type: object
        additionalProperties:
          type: string
        title: |-
          / Map chain -> resolved_address that contains other blockchain addresses.
          / This map will contain `current_chain_id` -> `resovled_address` if `resovled_address` is not None
  v1DomainEvent:
    type: object
    properties:
      transactionHash:
        type: string
        title: / Transaction hash where action occured
      timestamp:
        type: string
        format: uint64
        title: / Timestamp of this transaction
      fromAddress:
        type: string
        title: / Sender of transaction
      action:
        type: string
        title: / Optinal. Action name
  v1DomainWithAddress:
    type: object
    properties:
      resolvedAddress:
        type: string
      domainName:
        type: string
  v1HealthCheckResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/HealthCheckResponseServingStatus'
  v1QuickResolveResponse:
    type: object
    properties:
      domain:
        $ref: '#/definitions/v1DomainWithAddress'
  v1QuickResolveResponseManyAddresses:
    type: object
    properties:
      addresses:
        type: object
        additionalProperties:
          type: string
  v1QuickResolveResponseManyDomains:
    type: object
    properties:
      domains:
        type: object
        additionalProperties:
          type: string
  v1SearchReverseDomainResponse:
    type: object
    properties:
      resolvedTo:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Domain'
        title: |-
          List of domains that resolved to requested address
          Sorted by relevance, so first address could be displayed as main resolved address
      ownedBy:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Domain'
        title: List of domains owned by requested address
