[package]
name = "tac-operation-lifecycle-logic"
version = "0.1.0"
edition = "2021"


[dependencies]
tac-operation-lifecycle-entity = { path = "../tac-operation-lifecycle-entity" }
anyhow = "1.0"
blockscout-display-bytes = "1.0"
tracing = "0.1"

sea-orm = { version = "0.12.2", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "postgres-array",
] }


reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.6.1"
serde_json = "1.0"
futures = "0.3.31"
async-stream = "0.3.6"
tokio = "1.22"
chrono = "0.4.39"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
tower = { version = "0.5.2", features = ["limit"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }

[dev-dependencies]
blockscout-service-launcher = { version = "0.17.0", features = [ 
    
    "test-database", "database-0_12"
    
] }
pretty_assertions = "1.3"
tac-operation-lifecycle-migration = {path = "../tac-operation-lifecycle-migration"}
