[package]
name = "alliance-entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "^0" }
job-queue = { path = "../job-queue", features = ["entity"] }