[package]
name = "tac-operation-lifecycle-server"
version = "0.1.0"
edition = "2021"


[dependencies]
tac-operation-lifecycle-proto = { path = "../tac-operation-lifecycle-proto" }
tac-operation-lifecycle-logic = { path = "../tac-operation-lifecycle-logic" }
tac-operation-lifecycle-entity = { path = "../tac-operation-lifecycle-entity" }
tac-operation-lifecycle-migration = { path = "../tac-operation-lifecycle-migration" }
actix-web = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
blockscout-service-launcher = { workspace = true, features = ["database-1" ] }
config = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = [ "rt-multi-thread", "macros" ] }
tonic = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }


[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = [ "test-server","test-database","database-1"] }
tac-operation-lifecycle-entity = { path = "../tac-operation-lifecycle-entity" }
pretty_assertions = { workspace = true }
reqwest = { workspace = true, features = ["json"]}
futures = { workspace = true }
wiremock = { workspace = true }
# # Uncomment if needed
# mockall = "0.11"
# bytes = "1.5.0"
# hex = "0.4.3"
rand = { workspace = true }
# rstest = "0.18.2"
# sea-orm = { version = "*", features = [ "sqlx-sqlite" ]}
# tokio-stream = { version = "0.1", features = ["net"] }
