[workspace]
resolver = "2"
members = [
    "stats",
    "stats-proto",
    "stats-server",
    "stats/migration",
    "stats/entity",
    "env-docs-generation",
]

[workspace.dependencies]
blockscout-client = { git = "https://github.com/blockscout/blockscout-rs/", rev = "506b821" }
blockscout-service-launcher = { version = "0.14.0" }
rstest = "0.23.0"
tokio-util = "0.7.12"
tonic = "0.8"
wiremock = "0.6.2"

# todo: update version after https://github.com/chronotope/chrono/pull/1600
# and remove patch
[patch.crates-io]
chrono = { git = "https://github.com/bragov4ik/chrono", branch = "v0.4.38-naive-week-checked-patch" }
